<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8" />

    <!-- Always force latest IE rendering engine (even in intranet) & Chrome Frame
    Remove this if you use the .htaccess -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

    <title>Ichi Framework</title>
    <meta name="description" content="Ichi Framework" />
    <meta name="author" content="Sergio Brocos" />

    <meta name="viewport" content="width=device-width; initial-scale=1.0" />

  </head>
	<body>
		<h1>WELCOME to ICHI FRAMEWORK</h1>
		<?php print $this->contenido(); ?>
	</body>
</html>