<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8" />

    <!-- Always force latest IE rendering engine (even in intranet) & Chrome Frame
    Remove this if you use the .htaccess -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

    <title><?php echo $this->getVarLayout('title'); ?></title>
    <meta name="description" content="Ichi Framework" />
    <meta name="author" content="Sergio Brocos" />
    <meta name="viewport" content="width=device-width; initial-scale=1.0" />

 <!-- CSS -->
    <link href="/bootstrap/css/bootstrap.css" rel="stylesheet">
    <link href="/css/style.css" rel="stylesheet">
    <link href="/bootstrap/css/bootstrap-responsive.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="shortcut icon" href="/bootstrap/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/bootstrap/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/bootstrap/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/bootstrap/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="/bootstrap/ico/apple-touch-icon-57-precomposed.png">
  </head>

  <body>
    <!-- Part 1: Wrap all page content here -->
    <div id="wrap">
        <div class="navbar navbar-inverse navbar-fixed-top">
          <div class="navbar-inner">
            <div class="container">
              <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </a>
              <a class="brand" href="/"><?php echo $this->getVarLayout('title'); ?></a>
              <div class="nav-collapse collapse">
                <ul class="nav">
                  <li class="active"><a href="/">Home</a></li>
                  <li><a href="/index/about">About</a></li>
                  <li><a href="#contact">Contact</a></li>
                </ul>

              </div><!--/.nav-collapse -->
            </div>
          </div>
        </div>
        <!-- Begin page content -->
        <div class="container contenido">
            <?php print $this->contenido(); ?>
        </div>

        <div id="push"></div>
    </div>

    <div id="footer">
      <div class="container">
        <p class="muted credit">
            &copy; <a href="http://ichiframework.es">Ichi Framework</a> 2012
        </p>
      </div>
    </div>
    <!-- Cargamos los JS al final para optimizar la carga de la página -->
    <script src="http://code.jquery.com/jquery-latest.js"></script>
    <script src="/bootstrap/js/bootstrap.min.js"></script>
</body>
</html>